spring.application.name=deploy-testing
server.port=8080

# Actuator configuration for monitoring & health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
