app_name: "deploy_testing_2"
framework: "springboot"
deployment_type: "compose"
environment: "production"
port: 8081
working_directory: "./"
install_command: "./mvnw dependency:resolve"
build_command: "./mvnw clean package -DskipTests"
start_command: "java -jar target/*.jar"
output_dir: "target"
